//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "node_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub node_id: String,
    pub neighbor_nodes: String,
    pub is_alive: bool,
    pub rpc_domain: String,
    pub rpc_port: i32,
    pub ws_domain: String,
    pub ws_port: i32,
    pub clock_info_index: i32,
    pub merge_log_index: i32,
    pub z_message_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
