//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "z_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub message_id: String,
    pub version: Option<i32>,
    pub r#type: i32,
    pub public_key: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub data: Vec<u8>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub signature: Option<Vec<u8>>,
    pub from: String,
    pub to: String,
    pub node_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
